apiVersion : apps/v1
kind : Deployment
metadata:
  name: my-web-deploy-replicas
  labels:
    app  : my-k8s-app
    env  : prod
    owner: SergeyKoptilin
spec:
  replicas: 3
  selector:
    matchLabels:
      project: xxx
  template:
    metadata:
      labels:
        project: xxx
    spec:
      containers:
        - name : xxx-web
          image: koptilinshub/k8sphp:latest
          ports:
            - containerPort: 80
